// <auto-generated />
using System;
using MercadoFrutas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MercadoFrutas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402213742_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MercadoFrutas.API.Models.Fruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnTemporada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<float>("StockKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Frutas");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.IngresoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CantidadKg")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<float>("PrecioPorKg")
                        .HasColumnType("real");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FrutaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("IngresosStock");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.PagoProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("PagosProveedores");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CantidadKg")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FrutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<float>("PrecioPorKg")
                        .HasColumnType("real");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FrutaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.IngresoStock", b =>
                {
                    b.HasOne("MercadoFrutas.API.Models.Fruta", "Fruta")
                        .WithMany()
                        .HasForeignKey("FrutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercadoFrutas.API.Models.Proveedor", "Proveedor")
                        .WithMany("Ingresos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruta");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.PagoProveedor", b =>
                {
                    b.HasOne("MercadoFrutas.API.Models.Proveedor", "Proveedor")
                        .WithMany("Pagos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.Venta", b =>
                {
                    b.HasOne("MercadoFrutas.API.Models.Fruta", "Fruta")
                        .WithMany()
                        .HasForeignKey("FrutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruta");
                });

            modelBuilder.Entity("MercadoFrutas.API.Models.Proveedor", b =>
                {
                    b.Navigation("Ingresos");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
